apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: churn_platform
    user: cmp_user
    secureJsonData:
      password: cmp_pass
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
